const items = [
    {
        id: 1,
        image: 'card10.jpg',
        company: 'Louis Philippe',
        item_name: 'Louis Philippe Permapress Navy striped Notched Lapel Blazer by Myntra',
        original_price: 15999,
        current_price: 7999,
        discount_percentage: 52,
        return_period: 14,
        delivery_date: '29 Oct 2023',
        rating: {
            stars: 4.8,
            count: 1400,
        },
    },
    {
        id: 2,
        image: 'card11.jpg',
        company: 'BlackBerrys',
        item_name: 'three Piece Z-Black Textured Formal Suit - Waves by Myntra',
        original_price: 14599,
        current_price: 8999,
        discount_percentage: 43,
        return_period: 14,
        delivery_date: '10 jan 2023',
        rating: {
            stars: 4.2,
            count: 15640,
        },
    },
    {
        id: 3,
        image: 'card12.jpg',
        company: 'Roster',
        item_name: 'Casual full shirt for mens by Myntra',
        original_price: 1155,
        current_price: 999,
        discount_percentage: 18,
        return_period: 14,
        delivery_date: '15 aug 2023',
        rating: {
            stars: 4.1,
            count: 1540,
        },
    },
    {
        id: 4,
        image: 'card1.webp',
        company: 'Carlton London',
        item_name: 'Rhodium-Plated CZ Floral Studs',
        original_price: 1045,
        current_price: 606,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.5,
            count: 1400,
        },
    },
    {
        id: 5,
        image: 'card13.jpg',
        company: 'Slonces',
        item_name: 'Light Green full soot for girls by Myntra',
        original_price: 1879,
        current_price: 1259,
        discount_percentage: 38,
        return_period: 14,
        delivery_date: '22 mar 2023',
        rating: {
            stars: 4.3,
            count: 1140,
        },
    },
    {
        id: 6,
        image: 'card14.jpg',
        company: 'Bkilios',
        item_name: 'printed soot for girls by Myntra',
        original_price: 999,
        current_price: 569,
        discount_percentage: 39,
        return_period: 14,
        delivery_date: '29 apr 2023',
        rating: {
            stars: 5.3,
            count: 1694,
        },
    },
    {
        id: 7,
        image: 'card15.jpg',
        company: 'msloip-ships',
        item_name: 'Printed green shirt for mens by Myntra',
        original_price: 1455,
        current_price: 799,
        discount_percentage: 48,
        return_period: 14,
        delivery_date: '25 Oct 2023',
        rating: {
            stars: 4.3,
            count: 140,
        },
    },
    {
        id: 8,
        image: 'card2.webp',
        company: 'Artisan Treasures',
        item_name: 'The Bewitching Butterflies - Statement Enamelled Studs by Everstylish',
        original_price: 1114,
        current_price: 789,
        discount_percentage: 23,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.0,
            count: 460,
        },
    },
    {
        id: 9,
        image: 'card16.jpg',
        company: 'choszor',
        item_name: 'Light yellow kurta for mens by Myntra',
        original_price: 1959,
        current_price: 899,
        discount_percentage: 68,
        return_period: 14,
        delivery_date: '10 nov 2023',
        rating: {
            stars: 3.9,
            count: 1250,
        },
    },
    {
        id: 10,
        image: 'card17.jpg',
        company: 'monsor-navey',
        item_name: 'Gray t-shirt for mensby Myntra',
        original_price: 855,
        current_price: 459,
        discount_percentage: 35,
        return_period: 14,
        delivery_date: '11 mar 2023',
        rating: {
            stars: 3.4,
            count: 123540,
        },
    },
    {
        id: 11,
        image: 'card18.jpg',
        company: 'Safari',
        item_name: 'Safari 32L bag blue color by Myntra',
        original_price: 3955,
        current_price: 1699,
        discount_percentage: 50,
        return_period: 14,
        delivery_date: '10 jun 2023',
        rating: {
            stars: 4.3,
            count: 1240,
        },
    },
    {
        id: 12,
        image: 'card19.jpg',
        company: 'Brilliant Baubles',
        item_name: 'Mahroon kurta for mens by Myntra',
        original_price: 1355,
        current_price: 899,
        discount_percentage: 36,
        return_period: 14,
        delivery_date: '10 sep 2023',
        rating: {
            stars: 4.3,
            count: 140,
        },
    },
    {
        id: 13,
        image: 'card7.webp',
        company: 'Brilliant Baubles',
        item_name: 'Zaveri Pearls Gold Plated Austrian Diamond Studded Drop Earrings (Onesize) by Myntra',
        original_price: 1455,
        current_price: 799,
        discount_percentage: 48,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.3,
            count: 140,
        },
    },
    {
        id: 14,
        image: 'card20.jpg',
        company: 'vos-box',
        item_name: ' Light pink kurti for girls by Myntra',
        original_price: 1755,
        current_price: 999,
        discount_percentage: 38,
        return_period: 14,
        delivery_date: '18 sep 2023',
        rating: {
            stars: 5.3,
            count: 14450,
        },
    },
    {
        id: 15,
        image: 'card8.webp',
        company: 'Crown Jewels',
        item_name: 'YouBella Gold-Plated Stone-Studded Classic Drop Earrings',
        original_price: 2899,
        current_price: 1599,
        discount_percentage: 43,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.6,
            count: 3425,
        },
    },
    {
        id: 16,
        image: 'card21.jpg',
        company: 'hex-bsy',
        item_name: 'Blazer color gray for mens by Myntra',
        original_price: 1455,
        current_price: 799,
        discount_percentage: 48,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 5.3,
            count: 14130,
        },
    },
    
    
    {
        id: 17,
        image: 'card3.webp',
        company: 'BijouX',
        item_name: 'Shining Diva White Contemporary Jhumkas ',
        original_price: 1645,
        current_price: 999,
        discount_percentage: 47,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.4,
            count: 896,
        },
    },
    {
        id: 18,
        image: 'card4.webp',
        company: 'Dazzling drops',
        item_name: 'Yellow Chimes White Contemporary Drop Earrings At Nykaa Fashion - Your Online',
        original_price: 876,
        current_price: 599,
        discount_percentage: 32,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 3.7,
            count: 11167,
        },
    },
    {
        id: 19,
        image: 'card5.webp',
        company: 'Ear Adorned',
        item_name: 'Zaveri Pearls Gold Plated Kundan Studded Drop Earrings(Onesize) by Myntra',
        original_price: 1399,
        current_price: 789,
        discount_percentage: 36,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.7,
            count: 487,
        },
    },
    {
        id: 20,
        image: 'card.6.webp',
        company: 'Earring Escapade',
        item_name: 'A Bohemian Tale - Embellished Oxidised Earrings (Teal Blue) by Everstylish',
        original_price: 1799,
        current_price: 1099,
        discount_percentage: 46,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.9,
            count: 1765,
        },
    },
   
    
]